export const homeObjOne = {
    id: 'sobre',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Formação',
    headLine:'Análise e Desenvolvimento de Sistemas',
    description: 'Servidor Público na CIA. Brasileira de Trens Urbanos(CBTU),Entusiasta da tecnologia.\nTecnologias utilizadas: Node, Firebase, React, React-Native,Bootstrap e Next. ',
    buttonLabel: 'Get Started',
    imgStart:false,
    img: '/images/IMG_20200710_124645.jpg',
    alt: 'Henri Michel',
    darkText: false,
    primary: true,
    boderCircle:true,
}

export const homeObjTwo = {
    id: 'portfolio',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Portifolio',
    headLine:'Projetos desenvolvidos',
    description: 'Mobile e Web',
    buttonLabel: 'Get Started',
    imgStart:true,
    img: '/images/undraw_progressive_app_m9ms.svg',
    alt: 'Portfolio',
    darkText: true,
    primary: false,
    boderCircle:false,
}

export const homeObThree = {
    id: 'contato',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Entre em contato',
    headLine:'Landing Page a ser construida',
    description: 'Inserir os contatos',
    buttonLabel: 'Get Started',
    imgStart:false,
    img: '/images/undraw_contact_us_15o2.svg',
    alt: 'Contato',
    darkText: false,
    primary: true,
    boderCircle:false,
}